on:
  push:
    brances:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout docker-compose
          git pull
          git merge --no-ff main -m "Auto-merge from main"
          git push
